# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arun.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='arun.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\narun.proto\"Q\n\x0c\x63lientUpload\x12\n\n\x02sz\x18\x01 \x01(\t\x12\x13\n\x0b\x66ilecontent\x18\x02 \x01(\t\x12\x0e\n\x06isdist\x18\x03 \x01(\x08\x12\x10\n\x08\x66ilename\x18\x04 \x01(\t\"m\n\nserverComm\x12\x1b\n\x13ServerCommunication\x18\x01 \x01(\t\x12\x13\n\x0blistOfFiles\x18\x02 \x01(\t\x12\x11\n\theartBeat\x18\x03 \x01(\t\x12\x0c\n\x04host\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x05 \x01(\x05\x62\x06proto3')
)




_CLIENTUPLOAD = _descriptor.Descriptor(
  name='clientUpload',
  full_name='clientUpload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sz', full_name='clientUpload.sz', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filecontent', full_name='clientUpload.filecontent', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isdist', full_name='clientUpload.isdist', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='clientUpload.filename', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=95,
)


_SERVERCOMM = _descriptor.Descriptor(
  name='serverComm',
  full_name='serverComm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ServerCommunication', full_name='serverComm.ServerCommunication', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='listOfFiles', full_name='serverComm.listOfFiles', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heartBeat', full_name='serverComm.heartBeat', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='serverComm.host', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='serverComm.port', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=206,
)

DESCRIPTOR.message_types_by_name['clientUpload'] = _CLIENTUPLOAD
DESCRIPTOR.message_types_by_name['serverComm'] = _SERVERCOMM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

clientUpload = _reflection.GeneratedProtocolMessageType('clientUpload', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTUPLOAD,
  __module__ = 'arun_pb2'
  # @@protoc_insertion_point(class_scope:clientUpload)
  ))
_sym_db.RegisterMessage(clientUpload)

serverComm = _reflection.GeneratedProtocolMessageType('serverComm', (_message.Message,), dict(
  DESCRIPTOR = _SERVERCOMM,
  __module__ = 'arun_pb2'
  # @@protoc_insertion_point(class_scope:serverComm)
  ))
_sym_db.RegisterMessage(serverComm)


# @@protoc_insertion_point(module_scope)
